name: create-dev-build
on:
  push:
    branches-ignore:
      - at91bootstrap-3.x
jobs:
  get_toolchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: '3.12'
      - run: pip install lastversion
