name: Edge Build

on:
  push:
    branches-ignore:
      - main  # Exclude main branch, run on all others

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [glasnost-9g10, glasnost-9g20]
        config: []
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up ARM Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          version: '14.2.Rel1'

      - name: Find Available Configs
        id: find_configs
        run: |
          CONFIGS=$(ls contrib/board/vd-rd/${{ matrix.target }}/*.defconfig | xargs -n 1 basename | sed 's/_uboot_defconfig//')
          echo "configs=$(echo $CONFIGS | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Build Configs
        run: |
          for CONFIG in $configs; do
            echo "Building $CONFIG for ${{ matrix.target }}..."
            make CROSS_COMPILE=arm-none-eabi- ${CONFIG}_uboot_defconfig
            make CROSS_COMPILE=arm-none-eabi-
          done

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bootloader-${{ matrix.target }}-${{ env.configs }}
          path: binaries/boot.bin
